[project]
name = "ilps-service-task-manager"
version = "0.1.0"
description = "ðŸ’¼ ÐœÐµÐ½ÐµÐ´Ð¶ÐµÑ€ Ð·Ð°Ð´Ð°Ñ‡ Ð¿Ð¾ Ð¾Ð±Ñ€Ð°Ð±Ð¾Ñ‚ÐºÐµ Ð°ÑƒÐ´Ð¸Ð¾ Ð² Ð¸Ð½Ñ„Ñ€Ð°ÑÑ‚Ñ€ÑƒÐºÑ‚ÑƒÑ€Ðµ ILPS"
authors = [
    {name = "Oidaho",email = "76991612+Oidaho@users.noreply.github.com"},
    {name = "Ronin-D",email = "100284945+Ronin-D@users.noreply.github.com"}
]
license = {text = "LICENSE"}
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "sqlalchemy (>=2.0.40,<3.0.0)",
    "pydantic (>=2.11.3,<3.0.0)",
    "pydantic-settings (>=2.8.1,<3.0.0)",
    "alembic (>=1.15.2,<2.0.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "httpx (>=0.28.1,<0.29.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "sse-starlette (>=2.2.1,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
repository = "https://github.com/FEFU-ILPS/service-task-manager"
"Bug Tracker" = "https://github.com/FEFU-ILPS/service-task-manager/issues"